### ISSUE TITLE
Add Zonis 

### ISSUE THREAD

**Issue by Skelmis** [disnake-era/awesome-disnake#1]
Zonis provides IPC for discord bots & dashboards in a clean way so I think it should be included.

https://GitHub.com/skelmis/zonis

**Comment by elenakrittik** [comment]
Oooh I haven't thought of such use case when looked through your repositories, this one should be included indeed! Is this description good with you: "Agnostic IPC for Python programs, useful for implementing dashboards."?

Also sorry for not responding earlier, i thought that given i am the org/repo owner i'll automatically get notifications for everything happening, but it's apparently not the case.

**Comment by Skelmis** [comment]
Sounds good to me

**Comment by elenakrittik** [comment]
Done in e4368b522fb3a95699d0fd9b98caced02abf2fdf 🎉
